import os
from agents.bidding_dialogue_agent import BiddingDialogueAgent
from simulators.dialogue_simulator import DialogueSimulator
from utils.character_generator import generate_character_description, generate_character_header, generate_character_system_message, generate_character_bidding_template
from utils.bid_parser import ask_for_bid
import numpy as np

